### ISSUE TITLE
[FEATURE] Better quotationsHighlight function

### ISSUE THREAD

**Issue by TTTaevas** [TTTaevas/CyberPop#11]
CyberPop's a website that uses JS on the client's side in order to automatically highlight certain stuff, specifically in what's called "lessons" thanks to the lessons.js file currently located in the root folder.  
The way highlighting works is by manipulating HTML elements' childNodes; JS divides the HTML's text nodes so it can add a span element with a CSS class, and what's within this span element is what ends up being highlighted.

quotationsHighlight is a function with the goal to highlight whatever is within double quotation marks (including themselves) but fails to fully fulfill this goal due to how it currently finds out which mark marks the beginning and which mark marks the end.  
Currently, it checks whether or not there's a space before or after the mark to figure that out, but the issue is that characters that are not from the alphabet should also be checked, such as new lines, parentheses, commas, dots and so on.

Therefore, some quotation marks are currently ignored by the function.

So, either use another method than checking for characters in order to tell which mark is at the beginning and which mark is at the end, or keep the method but make it check for more characters.  
End goal is the same at the end of the day: In lessons, everything within double quotation marks (including themselves) should get highlighted.

Examples of the issue can be found in the "Execute JS code by clicking on a HTML element" lesson, in the JS sub-category, which is in the web development category. [LINK](https://tttaevas.github.io/CyberPop/en/web-dev/js/execute-js-by-html-click.html)

PS: You're free to work on this as long as there's no assignee!

**Comment by aashu** [comment]
I would like to work on it.   If it is still unassigned

**Comment by AidanKenney** [comment]
Hi, I'd be happy to work on this!
