### ISSUE TITLE
Add a language selection menu

### ISSUE THREAD

**Issue by TTTaevas** [TTTaevas/CyberPop#5]
Currently, only the main page allows the user to switch languages on the website.
Add to either the header or the footer an intuitive menu to switch the website's language.

Essentially, it would change the language part of the URL, switching it from, for example, "fr" to "en"
https://tttaevas.github.io/CyberPop/fr/ -> https://tttaevas.github.io/CyberPop/en/
https://tttaevas.github.io/CyberPop/fr/web-dev/css/html-use-css-file.html (may not exist due to #3) -> https://tttaevas.github.io/CyberPop/en/web-dev/css/html-use-css-file.html

**Comment by Mooike** [comment]
Hey @TTTaevas ,
as a first-timer I would love to ship a fix for this. 👍

**Comment by TTTaevas** [comment]
o/ @Mooike 
A fix for that would be greatly appreciated, so feel free to go ahead and start fixing this!

**Comment by Mooike** [comment]
I just added the language selection

**Comment by jessebessette** [comment]
So is this project issue resolved?

**Comment by TTTaevas** [comment]
Not yet, pull request #8 is lacking some stuff  
Once merged, this issue will be resolved
