### ISSUE TITLE
Add translation to german 

### ISSUE THREAD

**Issue by Mooike** [TTTaevas/CyberPop#6]
Hey,
since I am native german  speaker I could add a german translation for the CyberPop website if that is something you want.

- [x] Main page (de/index.html)
- [ ] Web-dev HTML
- [ ] Web-dev CSS
- [ ] Web-dev JS

**Comment by TTTaevas** [comment]
Hey, I would definitely like a German translation for Cyberpop, thank you so much!

**Comment by Mooike** [comment]
I just added a german version of the index.html and added German as button in the apps index.html file

**Comment by Mooike** [comment]
Translation of the other content will follow soon...

**Comment by TTTaevas** [comment]
Hello! I'm taking the liberty to close this issue as it has become inactive.
If you (or somebody else) wish to come back to translating CyberPop to German, please feel free to open this issue again!
